services:
  postgres:
    image: postgres:17.0
    container_name: 'eshop-postgres'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - postgres_db:/var/lib/postgresql/data
    networks:
      - eshop

  redis:
    image: redis:latest
    container_name: 'eshop-redis'
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - eshop
    
  mongo:
     image: mongo
     container_name: 'eshop-mongo'
     ports:
       - 27017:27017
     restart: always
     environment:
       MONGO_INITDB_ROOT_USERNAME: sa
       MONGO_INITDB_ROOT_PASSWORD: sa1302139
     networks:
       - eshop

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'eshop-rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "nhatnam1302"
    networks:
      - eshop

  seq:
     image: datalust/seq:latest
     container_name: 'eshop-seq'
     ports:
        - 5341:5341
        - 8081:80
     volumes:
        - seq_data:/data
     environment:
        ACCEPT_EULA: Y
        SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
     networks:
        - eshop

volumes:
  postgres_db:
  redis:
    driver: local
  seq_data:

networks:
  eshop:
    name: eshop