services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./Deployment/Scripts/postgres-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - eshop-data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    networks:
      - eshop
  
  redis:
    image: redis:7.4.7
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - eshop_redis:/data
    networks:
      - eshop

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest" 
      RABBITMQ_DEFAULT_VHOST: "eshop01012025"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - eshop

  tenancy:
    image: ${DOCKER_REGISTRY-}eshop/tenancy
    container_name: tenancy
    restart: on-failure
    build:
      context: .
      dockerfile: Tenancy/src/EShop.Tenancy.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Username=tenancy;Password=tenancy-password-dev;Server=postgres;Port=5432;Database=eshop_tenancy
      - RedisOptions__Enabled=true
      - RedisOptions__ConnectionString=redis:6379
      - MasstransitConfiguration__Host=rabbitmq
      - MasstransitConfiguration__Port=5672
      - MasstransitConfiguration__VirtualHost=eshop01012025
      - MasstransitConfiguration__Username=guest
      - MasstransitConfiguration__Password=guest
      - Services__Authorization=http://authorization:8080
    ports:
      - "5001:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      start_period: 10s
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./common.env
    networks:
      - eshop

  authorization:
    image: ${DOCKER_REGISTRY-}eshop/authorization
    container_name: authorization
    restart: on-failure
    build:
      context: .
      dockerfile: Authorization/src/EShop.Authorization.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Username=authorization;Password=authorization-password-dev;Server=postgres;Port=5432;Database=eshop_authorization
      - RedisOptions__Enabled=true
      - RedisOptions__ConnectionString=redis:6379
      - MasstransitConfiguration__Host=rabbitmq
      - MasstransitConfiguration__Port=5672
      - MasstransitConfiguration__VirtualHost=eshop01012025
      - MasstransitConfiguration__Username=guest
      - MasstransitConfiguration__Password=guest
      - Services__Tenancy=http://tenancy:8080
    ports:
      - "5002:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./common.env
    networks:
      - eshop

volumes:
  eshop-data:
  eshop_redis:
  rabbitmq_data:

secrets:
  postgres_password:
    file: ./Deployment/postgres_password.txt

networks:
  eshop:
    name: eshop
    driver: bridge
