// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EShop.Catalog.Tests.Products.ChangeVariantPrice
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ChangeVariantPriceFeature : object, global::Xunit.IClassFixture<ChangeVariantPriceFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Products/ChangeVariantPrice", "ChangeVariantPrice", "    As a catalog manager\r\n    I want to change the price of a product variant\r\n  " +
                "  So that pricing can be updated without modifying other properties", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ChangeVariantPrice.feature"
#line hidden
        
        public ChangeVariantPriceFeature(ChangeVariantPriceFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
            global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                        "PermissionId"});
            table21.AddRow(new string[] {
                        "Catalog_ManageProducts"});
            table21.AddRow(new string[] {
                        "Catalog_ManageCategories"});
#line 7
    await testRunner.GivenAsync("System user with following permissions", ((string)(null)), table21, "Given ");
#line hidden
#line 11
    await testRunner.AndAsync("all features are available for System User", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "Reference",
                        "Slug"});
            table22.AddRow(new string[] {
                        "Electronics",
                        "ELEC001",
                        "electronics"});
#line 12
    await testRunner.AndAsync("System User has created the following category", ((string)(null)), table22, "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Products/ChangeVariantPrice/ChangeVariantPrice.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change the price of a variant")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ChangeVariantPrice")]
        [global::Xunit.TraitAttribute("Description", "Change the price of a variant")]
        public async global::System.Threading.Tasks.Task ChangeThePriceOfAVariant()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change the price of a variant", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Description",
                            "Slug",
                            "Tags",
                            "Images"});
                table23.AddRow(new string[] {
                            "Laptop Pro",
                            "A powerful laptop",
                            "laptop-pro",
                            "portable",
                            "https://img.example.com/lp1.jpg"});
#line 17
    await testRunner.GivenAsync("System User has created the following product under category \'ELEC001\'", ((string)(null)), table23, "Given ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Values",
                            "DisplayStyle"});
                table24.AddRow(new string[] {
                            "Color",
                            "Color",
                            "Red,Blue",
                            "Text"});
#line 20
    await testRunner.AndAsync("System user has added a variation dimension to the product \'Laptop Pro\'", ((string)(null)), table24, "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Sku",
                            "Price",
                            "DiscountPrice",
                            "Color"});
                table25.AddRow(new string[] {
                            "Red Laptop",
                            "SKU-RED",
                            "500",
                            "459.99",
                            "Red"});
#line 23
    await testRunner.AndAsync("System user has added a variant to the product \'Laptop Pro\'", ((string)(null)), table25, "And ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "Price",
                            "DiscountPrice"});
                table26.AddRow(new string[] {
                            "599",
                            "549.99"});
#line 26
    await testRunner.WhenAsync("System user changes the price of variant \'SKU-RED\' of product \'Laptop Pro\'", ((string)(null)), table26, "When ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Sku",
                            "Price",
                            "DiscountPrice",
                            "IsDefault"});
                table27.AddRow(new string[] {
                            "Red Laptop",
                            "SKU-RED",
                            "599",
                            "549.99",
                            "false"});
#line 29
    await testRunner.ThenAsync("the product \'Laptop Pro\' has the following variants", ((string)(null)), table27, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ChangeVariantPriceFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ChangeVariantPriceFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
