@Authorization_URL = http://localhost:5002
@Catalog_URL = http://localhost:5004
@Inventory_URL = http://localhost:5042

# ============================================
# AUTHENTICATION
# ============================================

POST {{Authorization_URL}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "owner-account@eshop-staging",
  "password": "owner.eshop-staing-123"
}

###

# Extract the access token from login response
# After running the login request above, copy the accessToken value and paste it below
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzY2U1NDRjLWMyYmQtNDZiYy04N2IwLTRlMjc2YTAyMTQ0NCIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjNWQ2NGZhMS04NDNlLTQ0NTgtODAyMy0zNzc4ODdlY2ZiOGEiLCJzdWIiOiJvd25lci1hY2NvdW50QGVzaG9wLXN0YWdpbmciLCJ0ZW5hbnRfaWQiOiJlc2hvcC1zdGFnaW5nIiwia2V5X2lkIjoiMzNjZTU0NGMtYzJiZC00NmJjLTg3YjAtNGUyNzZhMDIxNDQ0IiwibmJmIjoxNzgwNzQxMTkxLCJleHAiOjE3ODA3NDQ3OTEsImlhdCI6MTc4MDc0MTE5MSwiaXNzIjoiaHR0cDovL2F1dGhvcml6YXRpb24iLCJhdWQiOiJodHRwOi8vYXV0aG9yaXphdGlvbiJ9.sqnx-Rr2HpYWeyT4BvTNFpZ9MQbLfLm1tkvDZmEIryMvm4FhVNHTWid4O1gnpgzuOcQ0UYdWC_ybQURT8UUiWxZqgMP2t-gK5og2cjjkNGcIvrTwHcbQZP2iw9G35Ge71DtXxvQFrhFKzIOAgmp2jRbeXUfbzdyp1u4YMXPhBXJUVz8A4pjHz8xZcLIYJKxcB_sizWyifxzaHv1wccAGZiUmuwy82bM-I1_jYPeHNadYDIA19rHu5B0W43jzX7NGZCGYVcP9wgRSjHbUuKr6k3bqJwWOY9XiilWH7LQrYCyDaR3pb110g3RiWEnc8u1n7i-qWsG0GJ7LYoL72-8tAw

###


# ============================================
# CATALOG API ENDPOINTS
# ============================================

# Get Product by ID (Requires Authentication)
GET {{Catalog_URL}}/api/v1/products
Content-Type: application/vnd.api+json
Authorization: Bearer {{accessToken}}

###

# ============================================
# INVENTORY API ENDPOINTS
# ============================================

# Create Inventory (Requires Authentication)
POST {{Inventory_URL}}/api/v1/inventories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "productId": "911b2c0b-7924-484a-ad0a-fbd9fbf0b08a",
  "variantId": "214fe0df-9941-46f8-bb45-16ce39d9f3e6",
  "sku": "SHIRT-GRN-S",
  "stockAvailable": 50,
  "minimumStock": 0
}

###

# Get Inventories by Product ID (Requires Authentication)
GET {{Inventory_URL}}/api/v1/inventories?productId=911b2c0b-7924-484a-ad0a-fbd9fbf0b08a
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# Get Inventories by Product ID with Pagination (Requires Authentication)
GET {{Inventory_URL}}/api/v1/inventories?productId=3fa85f64-5717-4562-b3fc-2c963f66afa6&pageIndex=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

  
# Create Inventory (Requires Authentication)
PATCH {{Inventory_URL}}/api/v1/inventories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "variantId": "214fe0df-9941-46f8-bb45-16ce39d9f3e6"
}

###
