@Authorization_URL = http://localhost:5002
@Catalog_URL = http://localhost:5004
@Inventory_URL = http://localhost:5042

# ============================================
# AUTHENTICATION
# ============================================

POST {{Authorization_URL}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "owner-account@eshop-staging",
  "password": "owner.eshop-staing-123"
}

###

# Extract the access token from login response
# After running the login request above, copy the accessToken value and paste it below
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1ZDQ1MGJkLTVhY2UtNDdhOC1iZjY5LTAxYzM3ZGMwMjFiMiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzNzhkMTc0Ni04ZTk3LTQ5ODQtYjc0YS0yOTdhMTRiMzM2OTkiLCJzdWIiOiJvd25lci1hY2NvdW50QGVzaG9wLXN0YWdpbmciLCJ0ZW5hbnRfaWQiOiJlc2hvcC1zdGFnaW5nIiwia2V5X2lkIjoiODVkNDUwYmQtNWFjZS00N2E4LWJmNjktMDFjMzdkYzAyMWIyIiwibmJmIjoxNzgyMDI4OTA4LCJleHAiOjE3ODIwMzI1MDgsImlhdCI6MTc4MjAyODkwOCwiaXNzIjoiaHR0cDovL2F1dGhvcml6YXRpb24iLCJhdWQiOiJodHRwOi8vYXV0aG9yaXphdGlvbiJ9.oKYjLk0yj8-4zVPHwmNNUeQN59FUoDgQevshWqDgW5UEF96zNB2DyVIe2hB3Chs3az1gytKBUhxr_V5QBOBf0kZ-0Brjm6uwRX67829DlnkRDY8k5H5IsUx2VhJrL87HAUrcUzXiNWnhr8kNG6_in8baK1b8BHyAHSwbwh8MYwemwp8NBE2QLd5NFeRDQrDZM6oKv2IiDkhjqDwRd9tLrGgNszMsCAeDNQeN7ENdJsOSBJeXEjYkrDWEeg82nBsr02Pi42Eed1WM21b_6LSaEDNgDL1BPa41ZfxovS7JLRQxdfqrOU__oM15K3rPG-8l9HtHGAuMhBEFHAe6otiFMg

###


# ============================================
# CATALOG API ENDPOINTS
# ============================================

# Get Product by ID
GET {{Catalog_URL}}/api/v1/products
Content-Type: application/vnd.api+json
Authorization: Bearer {{accessToken}}

###

# ============================================
# INVENTORY API ENDPOINTS
# ============================================

# Create Inventory
POST {{Inventory_URL}}/api/v1/inventories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "productId": "911b2c0b-7924-484a-ad0a-fbd9fbf0b08a",
  "variantId": "214fe0df-9941-46f8-bb45-16ce39d9f3e6",
  "sku": "SHIRT-GRN-S",
  "stockAvailable": 50,
  "minimumStock": 0
}

###

# Get Inventories by Product ID
GET {{Inventory_URL}}/api/v1/inventories?productId=911b2c0b-7924-484a-ad0a-fbd9fbf0b08a
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# Get Inventories by Product ID with Pagination
GET {{Inventory_URL}}/api/v1/inventories?productId=3fa85f64-5717-4562-b3fc-2c963f66afa6&pageIndex=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

  
# Add inventory's stock available from Postgres to Redis
PATCH {{Inventory_URL}}/api/v1/inventories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "variantId": "214fe0df-9941-46f8-bb45-16ce39d9f3e6"
}

###
# ============================================
# INVENTORY API ENDPOINTS
# ============================================

# Create Reservation
POST {{Inventory_URL}}/api/v1/reservations
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "orderId": "911b2c0b-7924-484a-ad0a-fbd9fbf0b08a",
  "items": [
    {
      "variantId": "214fe0df-9941-46f8-bb45-16ce39d9f3e6",
      "quantity": 1
    }
  ]
}
