// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EShop.Identity.Tests.Organizations.Create
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class OrganizationCreationFeature : object, Xunit.IClassFixture<OrganizationCreationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Organizations/Create", "OrganizationCreation", "    As an Admin user of the system\r\n    I want to group users\r\n    So that I can " +
                "reflect real world organization structure these employees belong to and correspo" +
                "nding access level", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "OrganizationCreation.feature"
#line hidden
        
        public OrganizationCreationFeature(OrganizationCreationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "TenantId",
                        "TenantName",
                        "OwnerUsername",
                        "OwnerDisplayName",
                        "OwnerEmail"});
            table1.AddRow(new string[] {
                        "tenant-1",
                        "Tenant1",
                        "tenantOwner1@tenant-1",
                        "Tenant Owner1",
                        "owner@tenant1.com"});
            table1.AddRow(new string[] {
                        "tenant-2",
                        "Tenant2",
                        "tenantOwner2@tenant-2",
                        "Tenant Owner2",
                        "owner@tenant2.com"});
#line 7
    await testRunner.GivenAsync("following tenants added to the system", ((string)(null)), table1, "Given ");
#line hidden
#line 11
    await testRunner.AndAsync("all standard features were turned on for \'tenant-1\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                        "Username",
                        "TenantId"});
            table2.AddRow(new string[] {
                        "tenantOwner1@tenant-1",
                        "tenant-1"});
#line 12
    await testRunner.AndAsync("the following users are set up", ((string)(null)), table2, "And ");
#line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "PermissionId"});
            table3.AddRow(new string[] {
                        "Identity_ViewOrganizations"});
            table3.AddRow(new string[] {
                        "Identity_ManageOrganizations"});
#line 15
    await testRunner.AndAsync("user \'tenantOwner1@tenant-1\' has the following permissions", ((string)(null)), table3, "And ");
#line hidden
#line 19
    await testRunner.AndAsync("user \'tenantOwner1@tenant-1\' logs in to the system", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creating a new organization under the root organization")]
        [Xunit.TraitAttribute("FeatureTitle", "OrganizationCreation")]
        [Xunit.TraitAttribute("Description", "Creating a new organization under the root organization")]
        public async System.Threading.Tasks.Task CreatingANewOrganizationUnderTheRootOrganization()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a new organization under the root organization", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OrganizationNumber",
                            "Email",
                            "Description",
                            "ParentOrganizationId"});
                table4.AddRow(new string[] {
                            "child-org",
                            "Organization child of root",
                            "50000",
                            "child-org@eshop.ecommerce",
                            "Child organization",
                            "tenant-1"});
#line 22
    await testRunner.WhenAsync("User \'tenantOwner1\' creates a new organization under the root organization with t" +
                        "he following details", ((string)(null)), table4, "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OrganizationNumber",
                            "Email",
                            "Description",
                            "ParentOrganizationId"});
                table5.AddRow(new string[] {
                            "child-org",
                            "Organization child of root",
                            "50000",
                            "child-org@eshop.ecommerce",
                            "Child organization",
                            "tenant-1"});
#line 25
    await testRunner.ThenAsync("organization \'child-org\' has the following details", ((string)(null)), table5, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await OrganizationCreationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await OrganizationCreationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
