apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-PBFA97CFB590B2093
    url: http://prometheus:9090

    isDefault: true
    # proxy = Grafana server queries Prometheus, not the browser.
    # This is always correct for server-side datasources.
    access: proxy
    editable: false

    jsonData:
      timeInterval: "15s"
      httpMethod: POST
