// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EShop.Tenancy.Tests.Tenants.SetRateLimitPolicy
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SetTenantRateLimitPolicyFeature : object, global::Xunit.IClassFixture<SetTenantRateLimitPolicyFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Tenants/SetRateLimitPolicy", "Set tenant rate limit policy", "\tAs a System or Support user\r\n\tI want to set a tenant\'s rate-limit policy\r\n\tSo th" +
                "at tenant request limits reflect their plan and support decisions", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SetTenantRateLimitPolicy.feature"
#line hidden
        
        public SetTenantRateLimitPolicyFeature(SetTenantRateLimitPolicyFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
            global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                        "PermissionId"});
            table17.AddRow(new string[] {
                        "Users_ViewSystemSettings"});
            table17.AddRow(new string[] {
                        "Users_ManageSystemSettings"});
#line 7
 await testRunner.GivenAsync("System user with following permissions", ((string)(null)), table17, "Given ");
#line hidden
#line 11
 await testRunner.AndAsync("all features are available for System User", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Tenants/SetRateLimitPolicy/SetTenantRateLimitPolicy.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="System User sets a valid rate-limit policy for a tenant")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Set tenant rate limit policy")]
        [global::Xunit.TraitAttribute("Description", "System User sets a valid rate-limit policy for a tenant")]
        public async global::System.Threading.Tasks.Task SystemUserSetsAValidRate_LimitPolicyForATenant()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System User sets a valid rate-limit policy for a tenant", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OwnerUserName",
                            "OwnerEmail",
                            "PhoneNumber"});
                table18.AddRow(new string[] {
                            "test-tenant",
                            "Test Owner",
                            "test-owner",
                            "test-owner@eshop.com",
                            "\'123456789\'"});
#line 14
 await testRunner.GivenAsync("System User has registered tenants with following details", ((string)(null)), table18, "Given ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Domain",
                            "Scope",
                            "Unit",
                            "RequestsPerUnit",
                            "Burst"});
                table19.AddRow(new string[] {
                            "*",
                            "User",
                            "Minute",
                            "120",
                            "150"});
#line 17
 await testRunner.WhenAsync("System User sets the rate-limit policy for tenant \'test-tenant\' with following ru" +
                        "les", ((string)(null)), table19, "When ");
#line hidden
#line 20
 await testRunner.ThenAsync("the system responds with status \'NoContent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tenant user cannot set the rate-limit policy")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Set tenant rate limit policy")]
        [global::Xunit.TraitAttribute("Description", "Tenant user cannot set the rate-limit policy")]
        public async global::System.Threading.Tasks.Task TenantUserCannotSetTheRate_LimitPolicy()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tenant user cannot set the rate-limit policy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OwnerUserName",
                            "OwnerEmail",
                            "PhoneNumber"});
                table20.AddRow(new string[] {
                            "test-tenant",
                            "Test Owner",
                            "test-owner",
                            "test-owner@eshop.com",
                            "\'123456789\'"});
#line 23
 await testRunner.GivenAsync("System User has registered tenants with following details", ((string)(null)), table20, "Given ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Domain",
                            "Scope",
                            "Unit",
                            "RequestsPerUnit",
                            "Burst"});
                table21.AddRow(new string[] {
                            "*",
                            "User",
                            "Minute",
                            "120",
                            "150"});
#line 26
 await testRunner.WhenAsync("a tenant user of \'test-tenant\' sets the rate-limit policy with following rules", ((string)(null)), table21, "When ");
#line hidden
#line 29
 await testRunner.ThenAsync("the system responds with status \'Forbidden\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="System User cannot set an invalid rate-limit policy")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Set tenant rate limit policy")]
        [global::Xunit.TraitAttribute("Description", "System User cannot set an invalid rate-limit policy")]
        public async global::System.Threading.Tasks.Task SystemUserCannotSetAnInvalidRate_LimitPolicy()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System User cannot set an invalid rate-limit policy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OwnerUserName",
                            "OwnerEmail",
                            "PhoneNumber"});
                table22.AddRow(new string[] {
                            "test-tenant",
                            "Test Owner",
                            "test-owner",
                            "test-owner@eshop.com",
                            "\'123456789\'"});
#line 32
 await testRunner.GivenAsync("System User has registered tenants with following details", ((string)(null)), table22, "Given ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Domain",
                            "Scope",
                            "Unit",
                            "RequestsPerUnit",
                            "Burst"});
                table23.AddRow(new string[] {
                            "*",
                            "User",
                            "Minute",
                            "0",
                            ""});
#line 35
 await testRunner.WhenAsync("System User sets the rate-limit policy for tenant \'test-tenant\' with following ru" +
                        "les", ((string)(null)), table23, "When ");
#line hidden
#line 38
 await testRunner.ThenAsync("the system raise an error with message \'non-positive requestsPerUnit\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SetTenantRateLimitPolicyFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SetTenantRateLimitPolicyFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
