@Authorization_URL = http://localhost:5002
@Catalog_URL = http://localhost:5004
@Inventory_URL = http://localhost:5042
@Order_URL = http://localhost:5050


# ============================================
# AUTHENTICATION
# ============================================

POST {{Authorization_URL}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "owner-account@eshop-staging",
  "password": "owner.eshop-staing-123"
}

###

# Extract the access token from login response
# After running the login request above, copy the accessToken value and paste it below
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzY2U1NDRjLWMyYmQtNDZiYy04N2IwLTRlMjc2YTAyMTQ0NCIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzOTYxYTZmNy00NWRkLTQ0MzUtYjFmNC1mMDk1ZWIzNDkwYTgiLCJzdWIiOiJvd25lci1hY2NvdW50QGVzaG9wLXN0YWdpbmciLCJ0ZW5hbnRfaWQiOiJlc2hvcC1zdGFnaW5nIiwia2V5X2lkIjoiMzNjZTU0NGMtYzJiZC00NmJjLTg3YjAtNGUyNzZhMDIxNDQ0IiwibmJmIjoxNzgwNDkzMjg4LCJleHAiOjE3ODA0OTY4ODgsImlhdCI6MTc4MDQ5MzI4OCwiaXNzIjoiaHR0cDovL2F1dGhvcml6YXRpb24iLCJhdWQiOiJodHRwOi8vYXV0aG9yaXphdGlvbiJ9.jO0PlmefNtQxni-aQ3SPU_ALdGUcXPvqLTr-s5ZvHmcIA6A1JDJZIm09EE51rsWIzqob9dMdUbSs2WWX3AOIhMvPJ0FEqsvkMA0fNdfv_g4gouUJ5nNee6uPEOhpSoIKjXVotxuN9R4e2nbvVxbjsHxPwr0Nk81DGq6bgkVrCa_6ni8qZ0Gg0HQMHxqscGA5v0BNWDP0c2T5Md2lq5BC1HUOsV7gpAl4b-PF7mZ8TTZqY5sGt3YSyqVwL7luT6x_ldGM1jUoSiRhII_Drxxr6TpEthI0yMXZsdZDkYVAp5jObYaUTa67tIm-kFUP3fr81stM3n1X0Yog4IGsefOVTA

###


# ============================================
# CATALOG API ENDPOINTS
# ============================================

# Get Product by ID (Requires Authentication)
GET {{Catalog_URL}}/api/v1/products
Content-Type: application/vnd.api+json
Authorization: Bearer {{accessToken}}

###

# ============================================
# ORDER API ENDPOINTS
# ============================================

# Create Order (Requires Authentication)
POST {{Order_URL}}/api/v1/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "buyerId": "customer-test1",
  "orderItems": [
    {
      "variantId": "01957eea-c993-714f-bf4a-ca767716031d",
      "quantity": 10,
      "unitPrice": 990,
      "discount": 0
    }
  ]
}

###

