@Authorization_URL = http://localhost:5002
@Catalog_URL = http://localhost:5004
@Inventory_URL = http://localhost:5042
@Order_URL = http://localhost:5050


# ============================================
# AUTHENTICATION
# ============================================

POST {{Authorization_URL}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "owner-account@eshop-staging",
  "password": "owner.eshop-staing-123"
}

###

# Extract the access token from login response
# After running the login request above, copy the accessToken value and paste it below
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1ZDQ1MGJkLTVhY2UtNDdhOC1iZjY5LTAxYzM3ZGMwMjFiMiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5OWVhNzA2OC00OWFjLTRjMjgtOGJiZi02ZDY0Nzk5M2YzZTEiLCJzdWIiOiJvd25lci1hY2NvdW50QGVzaG9wLXN0YWdpbmciLCJ0ZW5hbnRfaWQiOiJlc2hvcC1zdGFnaW5nIiwia2V5X2lkIjoiODVkNDUwYmQtNWFjZS00N2E4LWJmNjktMDFjMzdkYzAyMWIyIiwibmJmIjoxNzgyMzEwMDY0LCJleHAiOjE3ODIzMTM2NjQsImlhdCI6MTc4MjMxMDA2NCwiaXNzIjoiaHR0cDovL2F1dGhvcml6YXRpb24iLCJhdWQiOiJodHRwOi8vYXV0aG9yaXphdGlvbiJ9.n-7BTD2pjJ1ntzVId1ArAj5lFyHPfxNfgZS8Aq0HZ6mowS196MToXLNEco_QivsGOE4OYa_zomNkZBH2-cOxyWWUtDiq7hWLrIq8wFFdF7Z_0z-doaVS5wR8A3KtS_TNLhTzqtShsvHUaI67zvdfBgzUULBRZdHsPNu_Iesny5xo0oeSG1_La9_09CLL24-cIVa69W3hpdCf1zPiDBzHphZszybKZ9OXXZREoQUr5GpQRjzZmNHkAXCmuucZWzoB-441DCopAC_SoCKNdOjKZtX_DBjQUR05vBPaEu7Gp6ezZ90xTiWaGiKcJkJB26eaKrJvOWMiOdsTdFstXQhMDg

###


# ============================================
# CATALOG API ENDPOINTS
# ============================================

# Get Product by ID (Requires Authentication)
GET {{Catalog_URL}}/api/v1/products
Content-Type: application/vnd.api+json
Authorization: Bearer {{accessToken}}

###

# ============================================
# ORDER API ENDPOINTS
# ============================================

# Create Order (Requires Authentication)
POST {{Order_URL}}/api/v1/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "buyerId": "customer-test1",
  "orderItems": [
    {
      "variantId": "214fe0df-9941-46f8-bb45-16ce39d9f3e6",
      "quantity": 110,
      "unitPrice": 990,
      "discount": 0
    }
  ]
}

###

