@Authorization_URL = http://localhost:5002
@Catalog_URL = http://localhost:5004
@Inventory_URL = http://localhost:5042
@Order_URL = http://localhost:5050


# ============================================
# AUTHENTICATION
# ============================================

POST {{Authorization_URL}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "owner-account@eshop-staging",
  "password": "owner.eshop-staing-123"
}

###

# Extract the access token from login response
# After running the login request above, copy the accessToken value and paste it below
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzY2U1NDRjLWMyYmQtNDZiYy04N2IwLTRlMjc2YTAyMTQ0NCIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1OTBjZDZjZS0zZTQzLTQ4YjEtYjkzYS04NDlkZGUzZDM4OGQiLCJzdWIiOiJvd25lci1hY2NvdW50QGVzaG9wLXN0YWdpbmciLCJ0ZW5hbnRfaWQiOiJlc2hvcC1zdGFnaW5nIiwia2V5X2lkIjoiMzNjZTU0NGMtYzJiZC00NmJjLTg3YjAtNGUyNzZhMDIxNDQ0IiwibmJmIjoxNzgwNDIwNDc4LCJleHAiOjE3ODA0MjQwNzgsImlhdCI6MTc4MDQyMDQ3OCwiaXNzIjoiaHR0cDovL2F1dGhvcml6YXRpb24iLCJhdWQiOiJodHRwOi8vYXV0aG9yaXphdGlvbiJ9.jDNS-w8glG4KKElJQlzEvHI3vbSLKuPDK0Y5xQid6sIFGGctDAA0yLihuCk0anqrP0aow-S_WH7AFhmFYboGQFNikkz22vqKKm2VSfzjW5AC9rcn__IeZBUp5pNJOlIoHo_6mY_LxqQA3u_Ly3lMh8lk1aMCoktEuBxTM4QfG78fkX-IRip0dYdpwl6aQaLKFuBjW81G0HYEZ4kC9j0Et1G5J5SDdyqLSMKbHQyqRsqtB5-n7vzprKC0VheNtjSJlMm-YiHMqRWzgI54Iu-NSncHsQjJrhWni7QzKvQ_b3yT_eIfTEAX5jNcyctFTtPaP1crQO1i-kd5EEWGTfnr1w

###


# ============================================
# CATALOG API ENDPOINTS
# ============================================

# Get Product by ID (Requires Authentication)
GET {{Catalog_URL}}/api/v1/products
Content-Type: application/vnd.api+json
Authorization: Bearer {{accessToken}}

###

# ============================================
# ORDER API ENDPOINTS
# ============================================

# Create Order (Requires Authentication)
POST {{Order_URL}}/api/v1/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "buyerId": "customer-test1",
  "orderItems": [
    {
      "variantId": "01957eea-c993-714f-bf4a-ca767716031d",
      "quantity": 10,
      "unitPrice": 990,
      "discount": 0
    }
  ]
}

###

