// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EShop.Tenancy.Tests.Tenants.EnableTenantFeature
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EnableTenantFeaturesFeature : object, global::Xunit.IClassFixture<EnableTenantFeaturesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Tenants/EnableTenantFeature", "EnableTenantFeatures", "\tAs System User\r\n\tI want to enable specific features for a tenant\r\n\tSo that the t" +
                "enant can access those features", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "EnableTenantFeature.feature"
#line hidden
        
        public EnableTenantFeaturesFeature(EnableTenantFeaturesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
            global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                        "PermissionId"});
            table9.AddRow(new string[] {
                        "Users_ViewSystemSettings"});
            table9.AddRow(new string[] {
                        "Users_ManageSystemSettings"});
#line 7
 await testRunner.GivenAsync("System user with following permissions", ((string)(null)), table9, "Given ");
#line hidden
#line 11
 await testRunner.AndAsync("all features are available for System User", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Tenants/EnableTenantFeature/EnableTenantFeature.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="System User enables a feature for a tenant")]
        [global::Xunit.TraitAttribute("FeatureTitle", "EnableTenantFeatures")]
        [global::Xunit.TraitAttribute("Description", "System User enables a feature for a tenant")]
        public async global::System.Threading.Tasks.Task SystemUserEnablesAFeatureForATenant()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System User enables a feature for a tenant", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OwnerUserName",
                            "OwnerEmail",
                            "PhoneNumber"});
                table10.AddRow(new string[] {
                            "test-tenant",
                            "Test Owner",
                            "test-owner",
                            "test-owner@eshop.com",
                            "\'123456789\'"});
#line 14
 await testRunner.GivenAsync("System User has registered tenants with following details", ((string)(null)), table10, "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "Description",
                            "State",
                            "Module"});
                table11.AddRow(new string[] {
                            "feature-id",
                            "Test Feature",
                            "A new feature for testing",
                            "Disabled",
                            "Core"});
#line 17
 await testRunner.AndAsync("System User has created a new system feature with following details", ((string)(null)), table11, "And ");
#line hidden
#line 20
 await testRunner.WhenAsync("System User enables the feature \'feature-id\' for tenant \'test-tenant\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "FeatureId",
                            "State"});
                table12.AddRow(new string[] {
                            "feature-id",
                            "Enabled"});
#line 21
 await testRunner.ThenAsync("the tenant \'test-tenant\' has following features", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="System User cannot enable a non-existing feature")]
        [global::Xunit.TraitAttribute("FeatureTitle", "EnableTenantFeatures")]
        [global::Xunit.TraitAttribute("Description", "System User cannot enable a non-existing feature")]
        public async global::System.Threading.Tasks.Task SystemUserCannotEnableANon_ExistingFeature()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System User cannot enable a non-existing feature", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OwnerUserName",
                            "OwnerEmail",
                            "PhoneNumber"});
                table13.AddRow(new string[] {
                            "test-tenant",
                            "Test Owner",
                            "test-owner",
                            "test-owner@eshop.com",
                            "\'123456789\'"});
#line 26
 await testRunner.GivenAsync("System User has registered tenants with following details", ((string)(null)), table13, "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "Description",
                            "State",
                            "Module"});
                table14.AddRow(new string[] {
                            "feature-id",
                            "Test Feature",
                            "A new feature for testing",
                            "Enabled",
                            "Core"});
#line 29
 await testRunner.AndAsync("System User has created a new system feature with following details", ((string)(null)), table14, "And ");
#line hidden
#line 32
 await testRunner.WhenAsync("System User enables the feature \'test-feature-id\' for tenant \'test-tenant\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("the system raise an error with message \'Feature is not found for the tenant.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="System User cannot enable an enabled feature")]
        [global::Xunit.TraitAttribute("FeatureTitle", "EnableTenantFeatures")]
        [global::Xunit.TraitAttribute("Description", "System User cannot enable an enabled feature")]
        public async global::System.Threading.Tasks.Task SystemUserCannotEnableAnEnabledFeature()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System User cannot enable an enabled feature", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "OwnerUserName",
                            "OwnerEmail",
                            "PhoneNumber"});
                table15.AddRow(new string[] {
                            "test-tenant",
                            "Test Owner",
                            "test-owner",
                            "test-owner@eshop.com",
                            "\'123456789\'"});
#line 36
 await testRunner.GivenAsync("System User has registered tenants with following details", ((string)(null)), table15, "Given ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name",
                            "Description",
                            "State",
                            "Module"});
                table16.AddRow(new string[] {
                            "feature-id",
                            "Test Feature",
                            "A new feature for testing",
                            "Enabled",
                            "Core"});
#line 39
 await testRunner.AndAsync("System User has created a new system feature with following details", ((string)(null)), table16, "And ");
#line hidden
#line 42
 await testRunner.WhenAsync("System User enables the feature \'feature-id\' for tenant \'test-tenant\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
 await testRunner.ThenAsync("the system raise an error with message \'Feature is already enabled for the tenant" +
                        ".\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await EnableTenantFeaturesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await EnableTenantFeaturesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
