// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EShop.Identity.Tests.Organizations.Update
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class OrganizationCreationFeature : object, Xunit.IClassFixture<OrganizationCreationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Organizations/Update", "Organization Creation", "\tAs a tenant user\r\n\tI want to update an organization", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "OrganizationUpdation.feature"
#line hidden
        
        public OrganizationCreationFeature(OrganizationCreationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
#line 6
 await testRunner.GivenAsync("Admin user with all permissions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.AndAsync("all standard features were turned on for test tenant", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update an existing organization")]
        [Xunit.TraitAttribute("FeatureTitle", "Organization Creation")]
        [Xunit.TraitAttribute("Description", "Update an existing organization")]
        public async System.Threading.Tasks.Task UpdateAnExistingOrganization()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update an existing organization", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "Name",
                            "test-organization"});
                table6.AddRow(new string[] {
                            "OrganizationNumber",
                            "22000"});
                table6.AddRow(new string[] {
                            "PhoneNumber",
                            "+477311593200"});
                table6.AddRow(new string[] {
                            "Email",
                            "organization@test.com"});
                table6.AddRow(new string[] {
                            "Address",
                            "Oslo"});
                table6.AddRow(new string[] {
                            "City",
                            "Oslo"});
                table6.AddRow(new string[] {
                            "Postcode",
                            "0105"});
                table6.AddRow(new string[] {
                            "Description",
                            "Marine services provider based in Norway"});
#line 10
 await testRunner.GivenAsync("Admin user has created a new organization with the following", ((string)(null)), table6, "Given ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "Name",
                            "test-organization"});
                table7.AddRow(new string[] {
                            "OrganizationNumber",
                            "20000"});
                table7.AddRow(new string[] {
                            "PhoneNumber",
                            "+477311593222"});
                table7.AddRow(new string[] {
                            "Email",
                            "organization@test.com"});
                table7.AddRow(new string[] {
                            "Address",
                            "Oslo"});
                table7.AddRow(new string[] {
                            "City",
                            "Oslo"});
                table7.AddRow(new string[] {
                            "Postcode",
                            "0105"});
                table7.AddRow(new string[] {
                            "Description",
                            "Marine services provider based in Norway"});
#line 20
 await testRunner.WhenAsync("Admin user updates the organization \'test-organization\' with the following", ((string)(null)), table7, "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table8.AddRow(new string[] {
                            "Name",
                            "test-organization"});
                table8.AddRow(new string[] {
                            "OrganizationNumber",
                            "20000"});
                table8.AddRow(new string[] {
                            "PhoneNumber",
                            "+477311593222"});
                table8.AddRow(new string[] {
                            "Email",
                            "organization@test.com"});
                table8.AddRow(new string[] {
                            "Address",
                            "Oslo"});
                table8.AddRow(new string[] {
                            "City",
                            "Oslo"});
                table8.AddRow(new string[] {
                            "Postcode",
                            "0105"});
                table8.AddRow(new string[] {
                            "Description",
                            "Marine services provider based in Norway"});
#line 30
 await testRunner.ThenAsync("organization \'test-organization\' has the following details", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await OrganizationCreationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await OrganizationCreationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
